### ISSUE TITLE
2020-08-17: [VWS/Covid19NotificationApp] Missing the "blootstellingsmeldingen" tag in the play store

### ISSUE THREAD

**Issue by the-programmer** [minvws/nl-covid19-notification-app-android#19]
### Describe the bug, issue or concern
In the google play store there is no mention of the tag "blootstellingsmeldingen".

### To Reproduce
On a supported android phone set to the dutch language:
- Open settings
- Open "Google"
- Open "COVID-19 Exposure Notifications"
- Scroll to "More information"
- Tap "More information"

This will lead to the following page: https://support.google.com/android/answer/9888358?hl=nl (dutch)

Under the section "Wat u nodig heeft om aan de slag te gaan" we have the following text:
> Als er een app beschikbaar is in uw regio, kunt u deze downloaden via de Play Store. Zoek naar 'blootstellingsmeldingen' of naar de naam van de app.

**Smartphone**
 - OS: Android

### Additional context
According to google you should search for "blootstellingsmeldingen" in the play store. However doing this does leads to the following page:
![Play store](https://user-images.githubusercontent.com/3088971/90426744-dc722700-e0c1-11ea-9966-4bcd95a1036f.png)
This might be because there is no mention of "blootstellingsmeldingen" on the play store listing of the app at https://play.google.com/store/apps/details?id=nl.rijksoverheid.en
It might be an idea to add this tag somehow. (Maybe even a screenshot of the "COVID-19 Exposure Notifications" open with the "CoronaMelder" logo.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
For the Play Store app this has now been resolved by Google and Play Store on the web should follow soon too.

**Comment by the-programmer** [comment]
Although I agree that the app has the official badge now.
![Screenshot_20200820-093538 (Small)](https://user-images.githubusercontent.com/3088971/90731402-f0887500-e2c9-11ea-803d-d0d48134219f.png)

If I search for the term "blootstellingsmeldingen" I still don't get the correct app there.
![Screenshot_20200820-093752 (Small)](https://user-images.githubusercontent.com/3088971/90731414-f54d2900-e2c9-11ea-9626-4fc991f3bd36.png)

**Comment by hvisser** [comment]
"Corona" will show it on a special page. It's not something we control though, Google is working on it. I'll leave this open until resolved.

**Comment by lpappalettera** [comment]
Has been resolved by Google:

<img width="1391" alt="Screenshot 2020-11-10 at 14 39 40" src="https://user-images.githubusercontent.com/19887671/98681211-ba0b4500-2362-11eb-8b69-dd7b1b28f3d4.png">
